name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.10.0
          - 4.09.1
          - 4.08.1
          - 4.08.0
          - 4.07.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache opam files
        id: cache-opam
        uses: actions/cache@v2
        if: runner.os != 'Windows'
        with:
          path: ~/.opam
          key: ${{ matrix.os }}-ocaml_${{ matrix.ocaml-version }}-opam

      - name: Set up opam on macOS
        if: steps.cache-opam.outputs.cache-hit == 'true' && runner.os == 'macOS'
        run: /usr/local/bin/brew install opam

      - name: Use OCaml ${{ matrix.ocaml-version }}
        if: steps.cache-opam.outputs.cache-hit != 'true' || runner.os == 'Linux'
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam exec -- make

      - run: make test

      - uses: actions/upload-artifact@v2
        with:
          name: binary for ${{ matrix.os }} OCaml ${{ matrix.ocaml-version }}
          path: src/unison
